name: Refresh Facebook Tokens

on:
  schedule:
    - cron: '0 3 * * *'  # كل يوم الساعة 3 صباحاً (أفضل من منتصف الليل)
  workflow_dispatch:      # يسمح بتشغيل يدوي من واجهة GitHub

jobs:
  refresh-tokens:
    runs-on: ubuntu-latest
    timeout-minutes: 30   # وقت أقصى 30 دقيقة
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: package.json

      - name: Install dependencies
        run: npm install axios firebase-admin

      - name: Run token refresh
        env:
          FACEBOOK_APP_ID: ${{ secrets.FACEBOOK_APP_ID }}
          FACEBOOK_APP_SECRET: ${{ secrets.FACEBOOK_APP_SECRET }}
          FIREBASE_SERVICE_ACCOUNT: ${{ secrets.FIREBASE_SERVICE_ACCOUNT }}
        run: node refresh-tokens.js

      - name: Upload logs on failure
        if: failure()
        uses: actions/upload-artifact@v3
        with:
          name: token-refresh-logs
          path: logs/
